{{- if and
       .Values.etherpad.enabled
       .Values.etherpad.extraFiles
}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.etherpad.fullname" . }}-extrafiles
  labels:
    {{- include "jitsi-meet.etherpad.labels" . | nindent 4 }}
data:
  {{- range $i, $f := .Values.etherpad.extraFiles }}
  extrafile-{{ $i }}: |
    {{- $f.content | nindent 4 }}
  {{- end }}
{{- end }}
